<%
//Constantes

ADMIN_LEVEL        = 3 //controle total sobre o sistema
CONSULTOR_LEVEL    = 1 //Apenas insere tarefas/mensagens para grupo e ve as tarefas
CONFIGURATOR_LEVEL = 2 //insere tarefas/mensagens para grupo e pessoal e ve as tarefas

CONFIG_QUERIES_FILE = "queries.xml"
CONFIG_ACCESS_FILE  = "access.xml"
CONFIG_DB_FILE      = "db.xml"

//Constantes usadas no sistema de geracao de codigo de barras
MAXIMUM_ID_DIGITS  = 6
CORDVIDA_CODE      = "B3009"
START_CODE_PATTERN = "="
END_CODE_PATTERN   = "00"

NEXTSTEP = 2
ERROR = -999

ACTION_LOGIN                       = 0
ACTION_INSERT_CLIENT_DATA          = 2
ACTION_UPDATE_CLIENT_DATA          = 3
ACTION_DELETE_CLIENT_DATA          = 36
ACTION_INSERT_USER                 = 4
ACTION_UPDATE_USER                 = 5
ACTION_DELETE_USER                 = 6
ACTION_UPDATE_CLIENT_QUESTIONARIO  = 7
ACTION_UPDATE_CLIENT_COLETA        = 8
ACTION_UPDATE_ENFERMEIRA           = 9
ACTION_INSERT_ENFERMEIRA           = 10
ACTION_UPDATE_HOSPITAL             = 11
ACTION_INSERT_HOSPITAL             = 12
ACTION_DELETE_HOSPITAL             = 36
ACTION_UPDATE_CLIENT_PROCESSAMENTO = 13
ACTION_UPDATE_CLIENT_BIO           = 14
ACTION_INSERT_CLIENT_EXAMES        = 15
ACTION_UPDATE_CLIENT_EXAMES        = 16
ACTION_UPDATE_CLIENT_FINANCEIRO    = 17
ACTION_INSERT_AMOSTRA_DATA         = 18
ACTION_UPDATE_AMOSTRA_DATA         = 19
ACTION_IMPORT_DATA_MONITORACAO     = 20
ACTION_SET_STATUS_USER_INACTIVE    = 21
ACTION_SET_STATUS_USER_ACTIVE      = 22
ACTION_DELETE_ENFERMEIRA           = 23
ACTION_UPDATE_OBSTETRA             = 24
ACTION_INSERT_OBSTETRA             = 25
ACTION_DELETE_OBSTETRA             = 26
ACTION_START_PROCESSAMENTO         = 27
ACTION_UPDATE_TRANSPORTE_COLETA    = 28
ACTION_UPDATE_USER_DETAILS         = 29
ACTION_INSERT_INTERACAO_OBSTETRA   = 30
ACTION_UPDATE_INTERACAO_OBSTETRA   = 31
ACTION_DELETE_INTERACAO_OBSTETRA   = 32
ACTION_INSERT_INTERACAO_CLIENT   = 33
ACTION_UPDATE_INTERACAO_CLIENT   = 34
ACTION_DELETE_INTERACAO_CLIENT   = 35

STATUS_USER_INACTIVE = 1
STATUS_USER_ACTIVE   = 0
%>
